FROM openshift/base-centos7

MAINTAINER Nobody <nobody@example.com>

RUN yum install -y --enablerepo=centosplus \
    tar unzip bc which lsof java-1.8.0-openjdk java-1.8.0-openjdk-devel && \
    yum clean all -y

ENV BUILDER_VERSION 1.0
ENV MULE_VERSION 3.9.0
LABEL io.k8s.description="Platform for building Mule ${MULE_VERSION} CE applications" \
    io.k8s.display-name="Mule ${MULE_VERSION} builder 1.0" \
    io.openshift.expose-services="8080:http" \
    io.openshift.tags="builder,mule-${MULE_VERSION}"

RUN wget https://repository.mulesoft.org/nexus/content/repositories/releases/org/mule/distributions/mule-standalone/${MULE_VERSION}/mule-standalone-${MULE_VERSION}.tar.gz
RUN cd /opt && tar xvzf ~/mule-standalone-${MULE_VERSION}.tar.gz
RUN rm ~/mule-standalone-${MULE_VERSION}.tar.gz
RUN ln -s /opt/mule-standalone-${MULE_VERSION} /opt/mule

LABEL io.openshift.s2i.scripts-url=image:///usr/local/s2i
COPY ./s2i/bin/ /usr/local/s2i

RUN chown -R 1001:1001 /opt && chmod -R 777 /opt

# default user
USER 1001

CMD [ "usage" ]

# Set the default port for applications HTTP and event bus
EXPOSE 8080
